### ISSUE TITLE
Update existing tags

### ISSUE THREAD

**Issue by selbekk** [s-yadav/react-meta-tags#1]
I'd like this package to parse the DOM looking for existing tags, and if they exist, they should overwrite them instead of add new ones. If I set a `<title />` tag in my HTML, and then try to override it with this package, it doesn't get updated because the browser only uses the first `<title />` tag it sees.

This would also let us get rid of the `id`s that's currently in use.

**Comment by s-yadav** [comment]
Fixed in v0.3.0
