### ISSUE TITLE
Example generates warning

### ISSUE THREAD

**Issue by rgaino** [s-yadav/react-meta-tags#19]
Hi, on your readme, the example says  `<div class="wrapper">`, but shouldn't it be `<div className="wrapper">` instead? Happy to provide a PR if so.

Thanks!

**Comment by s-yadav** [comment]
Your comment is incomplete. No image or description.

**Comment by rgaino** [comment]
Sorry, forgot to format the html code. Comment updated now.

**Comment by s-yadav** [comment]
Fixed in v0.5.0
