### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by Jbonez87** [s-yadav/react-meta-tags#25]
The issue is in line 104 in meta_tags.js. There is no error handling if childStr is an empty string. I can make a pull request to fix this over the weekend if you'd like.

**Comment by s-yadav** [comment]
Sure PR is appreciated.

**Comment by Jbonez87** [comment]
I've made my pull request. Please review

**Comment by s-yadav** [comment]
Released this. v0.7.3

**Comment by AakashGfude** [comment]
For line 109 in lib/meta_tags.js :-  
`var childNodes = Array.prototype.slice.call(_this.temporaryElement.querySelector('.react-head-temp').children);`
 
I am getting Cannot read property 'children' of null. This line also needs to be handled ?
