### ISSUE TITLE
Duplicate meta tags when server-side rendering

### ISSUE THREAD

**Issue by raymestalez** [s-yadav/react-meta-tags#3]
Hi! Thank you for this awesome package, it is extremely helpful! I've encountered one issue though.

When I'm using it for server-side rendering, it seems like it's duplicating the meta info. I render it as html and insert it on server, but then when react loads on the frontend, it inserts them again.

Can you help me to figure out how I can prevent this?

**Comment by s-yadav** [comment]
Fixed in v0.3.0
