### ISSUE TITLE
React.PropTypes depreciated, use prop-types module instead.

### ISSUE THREAD

**Issue by ACregan** [s-yadav/react-meta-tags#4]
The console outputs a warning when using the latest version of react (15.5.4):

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

This is due to the depreciation of using react.proptypes. The new recommended approach is to use the seperate prop-types node module.

**Comment by blteblte** [comment]
bump

**Comment by matthewshirley** [comment]
PR #6 resolves this. Seemed to work perfectly on React 16. You can install it with my git repo if there is a delay with the merge.

**Comment by s-yadav** [comment]
Fixed on 0.2.0
